### ISSUE TITLE
Not working with node 12

### ISSUE THREAD

**Issue by SebTVisage** [import-js/eslint-import-resolver-typescript#143]
Greetings. When trying to use the plugin under node 12 (cannot upgrade for now), i get this error many times:
```
visage-server:    1:1   warning  Resolve error: Cannot find module 'node:fs'
visage-server: Require stack:
visage-server: - /Users/ouistiti/projects/visage-monorepo/back/api/node_modules/eslint-import-resolver-typescript/lib/index.cjs
visage-server: - /Users/ouistiti/projects/visage-monorepo/back/api/node_modules/eslint-module-utils/resolve.js
visage-server: - /Users/ouistiti/projects/visage-monorepo/back/api/node_modules/eslint-plugin-import/lib/rules/no-unresolved.js
visage-server: - /Users/ouistiti/projects/visage-monorepo/back/api/node_modules/eslint-plugin-import/lib/index.js
visage-server: - /Users/ouistiti/projects/visage-monorepo/back/api/node_modules/eslint/lib/config/plugins.js
visage-server: - /Users/ouistiti/projects/visage-monorepo/back/api/node_modules/eslint/lib/config.js
visage-server: - /Users/ouistiti/projects/visage-monorepo/back/api/node_modules/eslint/lib/cli-engine.js
visage-server: - /Users/ouistiti/projects/visage-monorepo/back/api/node_modules/eslint/lib/cli.js
visage-server: - /Users/ouistiti/projects/visage-monorepo/back/api/node_modules/eslint/bin/eslint.js
visage-server:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
visage-server:     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
visage-server:     at Module.require (internal/modules/cjs/loader.js:887:19)
visage-server:     at require (internal/modules/cjs/helpers.js:74:18)
visage-server:     at Object.<anonymous> (/Users/ouistiti/projects/visage-monorepo/back/api/node_modules/eslint-import-resolver-typescript/lib/index.cjs:5:10)
visage-server:     at Module._compile (internal/modules/cjs/loader.js:999:30)
visage-server:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
visage-server:     at Module.load (internal/modules/cjs/loader.js:863:32)
visage-server:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
visage-server:     at Module.require (internal/modules/cjs/loader.js:887:19)  import/no-unresolved
```

which is not surprising since the `node:` prefix to import native node modules is not supported on node 12.

I'm going to fork & remove the prefix for my needs. Will you accept a PR? Or do you just not support node 12 anymore?

**Comment by JounQin** [comment]
```json
{
  "engines": {
    "node": "^12.20.0 || ^14.18.0 || >=16.0.0"
  }
}
```
